---

- name: install git
  apt:
    name: git
    update_cache: yes
  become: yes

- name: create group
  group:
    name: "{{ devstack_user }}"
  become: yes

- name: create user
  user:
    name: "{{ devstack_user }}"
    group: "{{ devstack_user }}"
    createhome: yes
    password: "{{ stack_password }}"
  become: yes

- name: create devstack path folder, ownership, group and mode
  file:
    path: "{{ devstack_path }}"
    state: directory
    mode: 0755
    owner: "{{ devstack_user }}"
    group: "{{ devstack_user }}"
    recurse: yes
  become: yes

- name: create devstack dest folder, ownership, group and mode
  file:
    path: "{{ devstack_dest }}"
    state: directory
    mode: 0755
    owner: "{{ devstack_user }}"
    group: "{{ devstack_user }}"
    recurse: yes
  become: yes

- name: allow user group to have passwordless sudo
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ devstack_user }}"
      line: "{{ devstack_user }} ALL=(ALL) NOPASSWD: ALL"
  become: yes

- name: checkout devstack
  git:
    repo: "{{ devstack_repo }}"
    dest: "{{ devstack_path }}"
    version: "{{ devstack_branch }}"
    accept_hostkey: yes
    force: yes
  become_user: "{{ devstack_user }}"
  become: yes

#- name: allow user group to have passwordless sudo
#  lineinfile:
#      dest: "{{ devstack_path }}/tools/install_pip.sh"
#      state: present
#      regexp: "^pip_install -U setuptools"
#      line: "pip_install -U setuptools==18.2"
#  become_user: "{{ stack_user }}"
#  become: yes

- name: copy local.conf
  template:
    src: local.conf.j2
    dest: "{{ devstack_path }}/local.conf"
  become_user: "{{ devstack_user }}"
  become: yes

- name: copy autostack.sh
  template:
    src: autostack.sh
    dest: "/home/{{ devstack_user }}/autostack.sh"
    mode: 0755
    owner: "{{ devstack_user }}"
  become_user: "{{ devstack_user }}"
  become: yes

- name: unstack devstack
  command: "{{ devstack_path }}/unstack.sh"
  ignore_errors: true
  become_user: "{{ devstack_user }}"
  become: yes

- name: waiting for devstack installation
  command: "/home/{{ devstack_user }}/autostack.sh"
  become_user: "{{ devstack_user }}"
  become: yes

#- name: source openrc in profile
#  lineinfile: dest=/home/{{ devstack_user }}/.profile regexp=".*openrc" line='. {{ devstack_path }}/openrc'

#- name: enable external interface
#  command: ip link set dev {{ external_interface }} up
#  become: True

#- name: add port to br-ex bridge
#  shell: /usr/bin/ovs-vsctl add-port br-ex {{ external_interface }}
#  become: True

#- name: destroy default network of libvirt
#  shell: /usr/bin/virsh net-destroy default
#  become: True
