---

- name: install git
  apt:
    name: git
    update_cache: yes
  become: yes

- name: create group
  group:
    name: "{{ stack_user }}"
  become: yes

- name: create user
  user:
    name: "{{ stack_user }}"
    group: "{{ stack_user }}"
    createhome: yes
    password: "{{ stack_password }}"
  become: yes

- name: create devstack path folder, ownership, group and mode
  file:
    path: "{{ devstack_path }}"
    state: directory
    mode: 0755
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    recurse: yes
  become: yes

- name: create devstack dest folder, ownership, group and mode
  file:
    path: "{{ devstack_dest }}"
    state: directory
    mode: 0755
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    recurse: yes
  become: yes

- name: allow user group to have passwordless sudo
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ stack_user }}"
      line: "{{ stack_user }} ALL=(ALL) NOPASSWD: ALL"
  become: yes

- name: checkout devstack
  git:
    repo: "{{ devstack_repo }}"
    dest: "{{ devstack_path }}"
    version: "{{ devstack_branch }}"
    accept_hostkey: yes
    force: yes
  become_user: "{{ stack_user }}"
  become: yes

- name: checkout requirements for openstacksdk version conflict
  git:
    repo: "https://github.com/openstack/requirements.git"
    dest: "{{ devstack_dest }}/requirements"
    version: "{{ devstack_branch }}"
    accept_hostkey: yes
    force: yes
  become_user: "{{ stack_user }}"
  become: yes
  when: openstack_version == 'mitaka'

- name: setup openstacksdk===0.9.12 in upper-constraints.txt
  lineinfile:
      dest: "{{ devstack_dest }}/requirements/upper-constraints.txt"
      state: present
      regexp: "^openstacksdk===0.8"
      line: "openstacksdk===0.9.12"
  become_user: "{{ stack_user }}"
  become: yes
  when: openstack_version == 'mitaka'

#- name: allow user group to have passwordless sudo
#  lineinfile:
#      dest: "{{ devstack_path }}/tools/install_pip.sh"
#      state: present
#      regexp: "^pip_install -U setuptools"
#      line: "pip_install -U setuptools==18.2"
#  become_user: "{{ stack_user }}"
#  become: yes

- name: copy local.conf
  template:
    src: local.conf.j2
    dest: "{{ devstack_path }}/local.conf"
  become_user: "{{ stack_user }}"
  become: yes

- name: copy autostack.sh
  template:
    src: autostack.sh
    dest: "/home/{{ stack_user }}/autostack.sh"
    mode: 0755
    owner: "{{ stack_user }}"
  become_user: "{{ stack_user }}"
  become: yes

- name: copy screen_restart.sh
  template:
    src: screen_restart.sh
    dest: "{{ devstack_path }}/screen_restart.sh"
    mode: 0755
    owner: "{{ stack_user }}"
  become_user: "{{ stack_user }}"
  become: yes

- name: unstack devstack
  command: "{{ devstack_path }}/unstack.sh"
  ignore_errors: true
  become_user: "{{ stack_user }}"
  become: yes

- name: waiting for devstack installation
  command: "/home/{{ stack_user }}/autostack.sh"
  become_user: "{{ stack_user }}"
  become: yes

#- name: Make sure 'localhost' entry exists in /etc/hosts
#  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 devstack localhost' owner=root group=root mode=0644

#- name: source openrc in profile
#  lineinfile: dest=/home/{{ devstack_user }}/.profile regexp=".*openrc" line='. {{ devstack_path }}/openrc'

#- name: enable external interface
#  command: ip link set dev {{ external_interface }} up
#  become: True

#- name: add port to br-ex bridge
#  shell: /usr/bin/ovs-vsctl add-port br-ex {{ external_interface }}
#  become: True

#- name: destroy default network of libvirt
#  shell: /usr/bin/virsh net-destroy default
#  become: True
